export const SEO_CONFIG = {
  siteName: 'OpsPilot - Field Operations Management Software',
  siteUrl: 'https://opspilot.in',
  defaultTitle: 'OpsPilot - Field Operations Management Software | CRM, Attendance & Team Management',
  defaultDescription: 'OpsPilot is a powerful SaaS platform for field operations teams. Manage leads, track attendance with selfie verification, run payroll, and empower your telecallers, managers, HR, and executives — all in one place.',

  keywords: [
    'OpsPilot',
    'field operations software',
    'CRM software India',
    'attendance management system',
    'telecaller CRM',
    'field sales management',
    'employee attendance tracking',
    'lead management software',
    'HR management software',
    'SaaS CRM',
    'team management software',
    'field force management',
    'sales team CRM',
    'mobile CRM India',
    'attendance with selfie verification',
    'payroll management software',
    'leave management system',
    'sales pipeline management',
    'field worker management',
    'operations management platform',
    'employee portal',
    'manager portal',
    'telecaller portal',
    'HR portal',
    'executive dashboard',
    'multi-tenant SaaS',
    'business operations software',
    'small business CRM',
    'medium business ERP',
    'workforce management',
    'remote team management',
    'sales CRM India',
    'field service management',
    'employee performance tracking',
    'lead conversion software',
    'customer relationship management',
    'business management software India',
  ],

  business: {
    name: 'OpsPilot',
    type: 'SoftwareApplication',
    description: 'OpsPilot is a comprehensive SaaS platform for managing field operations, telecaller teams, attendance tracking, lead management, HR workflows, and payroll — built for businesses that want to streamline their ground operations.',
    email: 'support@opspilot.in',
    applicationCategory: 'BusinessApplication',
    operatingSystem: 'Web, Android, iOS',
    offers: {
      priceCurrency: 'INR',
      price: '0',
      description: 'Free trial available. Subscription plans for teams of all sizes.',
    },
    features: [
      'Telecaller CRM & Lead Management',
      'Attendance Tracking with Selfie Verification',
      'GPS-based Check-in & Check-out',
      'Payroll & Salary Management',
      'Leave Request Management',
      'Manager & HR Portals',
      'Executive Analytics Dashboard',
      'Multi-tenant Architecture',
      'Role-based Access Control',
      'Real-time Notifications',
      'Lead Remarks & Follow-up Tracking',
      'Sales Pipeline Management',
    ],
  },

  openGraph: {
    type: 'website',
    locale: 'en_IN',
    title: 'OpsPilot - Field Operations Management Software',
    description: 'Manage your entire field operations team from one powerful SaaS platform. CRM, attendance tracking, payroll, leads, and more — built for growing businesses.',
    siteName: 'OpsPilot',
  },

  twitter: {
    card: 'summary_large_image',
    title: 'OpsPilot - Field Operations Management Software',
    description: 'Powerful SaaS platform for field sales, telecallers, and operations teams. CRM, attendance, payroll, and lead management in one app.',
  },
};
